### ISSUE TITLE
Widget indicator not working when using CircularPercentIndicator Arc

### ISSUE THREAD

**Issue by fabianosanttana** [diegoveloper/flutter_percent_indicator#123]
Im trying to use circular percent indicator but there is an problem, my widget indicator is displayed in another place that is not end of my percentage.

<img width="312" alt="Screen Shot 2021-07-20 at 19 49 47" src="https://user-images.githubusercontent.com/27648537/126405137-b53d227b-1ec6-4191-a990-b50f2d3787a6.png">

```
CircularPercentIndicator(
                  radius: 120.0,
                  animation: true,
                  animationDuration: 2000,
                  lineWidth: 10.0,
                  percent: 0.4,
                  reverse: false,
                  arcType: ArcType.FULL,
                  startAngle: 0.0,
                  animateFromLastPercent: true,
                  circularStrokeCap: CircularStrokeCap.round,
                  backgroundColor: Colors.transparent,
                  linearGradient: const LinearGradient(
                    begin: Alignment.centerLeft,
                    end: Alignment.centerRight,
                    tileMode: TileMode.clamp,
                    stops: [0.0, 1.0],
                    colors: <Color>[
                      Colors.yellow,
                      Colors.red,
                    ],
                  ),
                  widgetIndicator: Center(
                    child: Container(
                      height: 30,
                      width: 30,
                      decoration: BoxDecoration(
                        color: yellowStone.withOpacity(.5),
                        borderRadius: BorderRadius.circular(50),
                      ),
                      padding: const EdgeInsets.all(5),
                      child: Container(
                        decoration: BoxDecoration(
                          color: yellowStone.withOpacity(1),
                          borderRadius: BorderRadius.circular(50),
                        ),
                      ),
                    ),
                  ),
                  arcBackgroundColor: Colors.red,
                )
```

**Comment by diegoveloper** [comment]
Fixed on the latest version.

**Comment by chrizstone** [comment]
This is not fixed?! I took exactly same code as @fabianosanttana. Have the same issue with version 4.0.0... Any updates here?
